name: Reconcile Betting Results

on:
  schedule:
    # This runs at 8:00 AM UTC every day.
    - cron: '0 8 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  reconcile:
    runs-on: ubuntu-latest
    steps:
      - name: Call the reconcile API endpoint
        run: curl --request GET '${{ secrets.RECONCILE_URL }}'
